name: CI

# Workflow description
# This workflow does the following:
# 1. Sets up Node.js and installs the necessary dependencies.
# 2. Runs linters to check the code quality.
# 3. Runs unit tests.
# 4. If linters or tests fail, the workflow stops and does not allow the commit or pull request.
# 5. Notifies the team if there are failures in linters or tests.

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run linters
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Notify team on failure
        if: failure()
        run: echo "Tests or linters failed. Please check the logs for details."
